version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: frontend/frontend.Dockerfile
    image: s0x45ker/flask-book-store-web:v2
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHON_PATH=/app
    working_dir: /app
    depends_on:
      - db
    volumes:
      - ./:/app 
    networks:
      - flask-network

  db:
    build: 
      context: .
      dockerfile: backend/backend.Dockerfile
    image: s0x45ker/flask-book-store-db:v2
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask-network

volumes:
  postgres_data:

networks:
  flask-network:
    driver: bridge
