version: '3.8'

services:
  web:
    image: s0x45ker/flaskstore_web:v1
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

    depends_on:
      - db
    volumes:
      - ./flask_frontend:/app
    networks:
      - flask-network

  db:
    image: s0x45ker/flaskstore_db:v1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgress_data:/var/lib/postgresql/data
    networks:
      - flask-network

volumes:
  postgress_data:

networks:
  flask-network:
    driver: bridge